name = "rocket-science"
version = "1.0.0"
license = "BSD"
author = ["Damian Rouson", "Brad Richardson", "Brian Laubacher"]
maintainer = "damian@sourceryinstitute.org"
copyright = "2020-2021 Sourcery Institute"
